---
title: "rawReadeR Compatibility"
author: "Tom Wilson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{rmarkdown::render()}
---


While the `.raw` file type is unique to Thermo Mass Spectrometers, each `.raw` file can contain differing elements depending on __(1)__ the version of Xcalibur installed on the instrument and __(2)__ the mass spectrometry method implemented. The following tables document the status of useability acorss Xcalibur versions and method types for each version of `rawReadeR`

Each version is contained in it's own isolated branch, and once stable will be mereged to the master branch. Bleeding edge versions will always be available from the corresponding branch. Stable versions will be frequently released _via_ GitHub and deposited with Zenodo.


### Glossay

|Abbreviation|Definition|
|:----------:|:--------:|
| FT-MS|Fourier Transform Mass Spectrometry
| dd| Data Dependant
| IT| Ion Trap
| HCD| Higher Collision Dissociation
| CID| Collision Induced Dissociation
| PDA| Photodiode Array
| ESI| Electrospray Ionisation
| NSI| nano-Spray Ionisation
| MSn| Tandem Mass Spectrometry



### Tested `.RAW` File Versions


|rawReadeR Version   | .RAW Version|
|:--------------------:|:-------------:|
|0.1.0| 
|0.1.1|
|0.1.2| 
|0.1.3|
|0.1.4|
|0.1.5|


### Tested Method Types


|rawReadeR Version     | Method
|:--------------------:|:-------------:|
|0.1.0| FT-MS1
|0.1.1| FT-MS1
|0.1.2| FT-MS1,FT-MS1 + dd-HCD-FT-MS2
|0.1.3|
|0.1.4|
|0.1.5|
